
tbspcie-objs	:= tbspcie-core.o tbspcie-cards.o tbspcie-i2c.o

obj-$(CONFIG_DVB_TBSPCIE) += tbspcie.o

ccflags-y += -Idrivers/media/tuners
ccflags-y += -Idrivers/media/dvb-core
ccflags-y += -Idrivers/media/dvb-frontends

